### ISSUE TITLE
Excel Formulas cause problems

### ISSUE THREAD

**Issue by bape234** [christophano/CsvHelper.Excel#8]
When trying to read an Excel File with Formulas, ClosedXML throws an Syntax Error. Check if this is related to CsvHelper.Excel or is the problem at ClosedXML.

referring to: https://stackoverflow.com/questions/46241763/c-sharp-csvhelper-csvhelper-excel-closedxml-giving-me-syntax-error-on-basic-cod

**Comment by christophano** [comment]
It looks like the consensus is that the exception is thrown from `ClosedXml`. I've tested loading workbooks containing formula's and they work just fine. If you can provide an example that reproduces the issue then I can investigate further.

Would appreciate if you clarified on your answer that this issue is within `ClosedXml`, not `CsvHelper` or `CsvHelper.Excel`!

Regarding your comment (on the stack overflow question) about having the header row on a row other than the first row, keep an eye on issue #4, as I really ought to get around to that soon.

**Comment by christophano** [comment]
@bape234 I've added a test in commit (4ba83b7bbd02846e64b5549e89a3dc93891c20f2) showing that CsvHelper.Excel works with formulas perfectly well - your issue was certainly with ClosedXml or DocumentFormat.OpenXml; both of which are outside of my control.
